# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    inputs:
      deploy_region:
        description: 'Countries to deploy the App'     
        required: true
        default: 'us mx co pe at pl'
  
jobs:
 
  deploy:
    runs-on: ubuntu-latest
    strategy:
        matrix: 
          region: ${{fromJson(github.event.inputs.deploy_region)}}
    steps:
      - name: Deployment region
        run: echo Deploying on region ${{ matrix.region }}

      - uses: actions/checkout@v2
