# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    inputs:
      deploy_region:
        description: 'Countries to deploy the App'     
        required: true
        default: 'us mx co pe at pl'
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Handle User Input
        id: set-regions
        run: |
          regions=`echo ${{ github.event.inputs.deploy_region }} | sed -e 's/^[[:space:]]*/"/' -e 's/[[:space:]]*$/"/' -e 's/[[:space:]]\{1,\}/","/g'`
          echo ::set-output name=regions::[$regions]
    outputs:
      regions: ${{ steps.set-regions.outputs.regions }}
 
  deploy:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
        matrix: 
          region: ${{fromJson(needs.setup.outputs.regions)}}
    steps:
      - name: Deployment region
        run: echo Deploying on region ${{ matrix.region }}

      - uses: actions/checkout@v2
